#Target_name : Dependencies
#<TAB>Command


target : quiz.c game.c help.c reset_score.c show_record.c fun.h
	gcc  quiz.c game.c help.c reset_score.c show_record.c -o all.out

run : target 
	./all.out
