name: Cppcheck-Static Code Quality Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cppcheck:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt -y install cppcheck
      - name: make
        run: make -C Implementation/ all
      - name: Run cppcheck
        run: cppcheck Implementation